### PR TITLE
Remove duplicate docs from the repo and change all links to point to …

### LINKED ISSUE #235: Refactor docs/website to organize and avoid duplication.
**Is your feature request related to a problem? Please describe.**

Our markdown documentation and website source code has a lot of duplicate content right now.

**Describe the solution you'd like**

We should find some clean way of making a single canonical source for our core documentation. This might be as simple as deleting the non-website copy of docs, or it could be something along the lines of an expanded build script for the website.

### PR DESCRIPTION
**Pull request by rajat404**
…the Hugo site

- Removed the markdown & image files which were duplicated in the hugo site.
- Please note that the files have been compared for any differences prior to deletion. No diffs were found b/w the copies.
- Replaced all references to the old doc files, with the hugo site markdown files. The same has been done for images.

Fixes #235 

**Release note**:

```release-note
- Unified source for all documentation: Henceforth all links pertaining to Pinnipied docs will redirect users to the project's static site hosted on https://pinniped.dev/
```

### CODE REVIEW

**Review by mattmoyer — DISMISSED** [review]
This looks great, thanks @rajat404! I think your suggestion about the images also sounds good.

**Comment by rajat404** [comment]
Great! Will make that change as well 🤟

**Comment by rajat404** [comment]
**Update:** I've made the changes regarding image links as well, given that it was a small change.

To be reviewed once the discussion on [this thread](https://kubernetes.slack.com/archives/C01BW364RJA/p1606754809086900) has been resolved.

**Review by mattmoyer — APPROVED** [review]
Thanks again @rajat404!

**Pull request merged**
