### PR TITLE
Use vmware-tanzu/carvel instead of the deprecated k14s/tap to install deps with brew

### PR DESCRIPTION
**Pull request by vicmarbev**
- Replace in the occurrences of `k14s/tap` in favor of `vmware-tanzu/carvel`  in the `Contributing.md` and `hack/prepare-for-integration-tests.sh`. This is to avoid the deprecation messages like:
  _Warning: k14s/tap/kapp has been deprecated because it Migrating tap to vmware-tanzu/carvel!_
  and
  _Warning: k14s/tap/ytt has been deprecated because it Migrating tap to vmware-tanzu/carvel!_

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by cfryanr — APPROVED** [review]
Thanks for this PR! Please sign the CLA following the instructions in the comment on this PR from the bot, and then we will be happy to merge it.

**Comment by vicmarbev** [comment]
Done!

**Comment by cfryanr** [comment]
> Done!

Thanks! As soon as it goes through an internal review process the bot will respond again, and then we will be able to merge. That usually takes a couple of days.

**Comment by cfryanr** [comment]
Merged main into PR, and merging to main now. Didn't wait for CI to run again since these docs are not covered by tests.

Thanks for your contribution @vicmarbev! Much appreciated!

**Pull request merged**
